mod cat;
mod cli;
mod decode;
mod encode;
mod formats;
mod grep;
mod info;
mod input;
mod output;
mod pipe;
mod qc;
mod revcomp;
mod sample;
mod split;
mod verify;

pub use cat::CatCommand;
pub use cli::{Cli, Commands};
pub use decode::DecodeCommand;
pub use encode::EncodeCommand;
pub use formats::FileFormat;
#[cfg(feature = "fuzzy")]
pub use grep::FuzzyArgs;
pub use grep::{GrepCommand, PatternFileArgs};
pub use info::InfoCommand;
pub use input::{InputBinseq, InputFile, MultiInputBinseq};
pub use output::{BinseqConfig, BinseqMode, Mate, OutputBinseq, OutputBinseqInherited, OutputFile};
pub use pipe::PipeCommand;
pub use qc::{QcCommand, QcOptions};
pub use revcomp::RevcompCommand;
pub use sample::SampleCommand;
pub use split::SplitCommand;
pub use verify::{VerifyCommand, VerifyOptions};
