//! Timing and parity guardrail for `bqtools grep` (and `split`, which shares the
//! matching engine). Compare a build from before a change with one from after:
//!
//! ```text
//! cargo run --release --example bench_grep -- ab    <old-bin> <new-bin>
//! cargo run --release --example bench_grep -- check <old-bin> <new-bin>
//! ```
//!
//! `ab` times both binaries on every case, alternating runs so machine drift
//! hits both equally, and flags anything more than 10% slower (best of `--runs`).
//! `check` runs every case single-threaded and compares a hash of the output.
//! Differences are not necessarily bugs; review each one.
//!
//! The fixture (seeded, 1M paired 150bp reads) is generated once into `--dir`.
//! Run-to-run noise is about 1-2%, but the fuzzy (sassy) cases move by up to ~9%
//! between builds with no source change (code layout): judge a fuzzy change
//! against an untouched fuzzy case (e.g. `fz_pc_*` against `fz_invert_count`).

use std::{
    collections::hash_map::DefaultHasher,
    fs::{self, File},
    hash::{Hash, Hasher},
    io::{BufWriter, Write},
    path::{Path, PathBuf},
    process::{Command, Stdio},
    time::{Duration, Instant},
};

use anyhow::{ensure, Result};
use clap::{Parser, Subcommand};
use rand::{rngs::StdRng, RngExt, SeedableRng};

#[derive(Parser)]
struct Cli {
    #[clap(subcommand)]
    mode: Mode,

    /// Where the fixture lives (generated on first use)
    #[clap(long, default_value = "/tmp/bqtools-bench", global = true)]
    dir: PathBuf,

    /// Read pairs in the fixture
    #[clap(long, default_value_t = 1_000_000, global = true)]
    records: usize,

    /// Timed runs per case and binary (after two warmups)
    #[clap(long, default_value_t = 5, global = true)]
    runs: usize,

    /// Threads passed to every timed command
    #[clap(long, default_value_t = 8, global = true)]
    threads: usize,
}

#[derive(Subcommand)]
enum Mode {
    /// Time both binaries on every case
    Ab { old: PathBuf, new: PathBuf },
    /// Compare the output of both binaries on every case
    Check { old: PathBuf, new: PathBuf },
}

struct Case {
    name: &'static str,
    args: Vec<String>,
}

/// The fixture's files, generated by `Fixture::ensure`.
struct Fixture {
    dir: PathBuf,
}
impl Fixture {
    fn path(&self, name: &str) -> String {
        self.dir.join(name).to_string_lossy().into_owned()
    }

    fn ensure(dir: &Path, records: usize, bin: &Path) -> Result<Self> {
        let fx = Self { dir: dir.into() };
        if dir.join(".done").exists() {
            return Ok(fx);
        }
        fs::create_dir_all(dir)?;
        let mut rng = StdRng::seed_from_u64(1);

        let (r1, r2) = (fx.path("r1.fq"), fx.path("r2.fq"));
        for path in [&r1, &r2] {
            let mut out = BufWriter::new(File::create(path)?);
            for i in 0..records {
                writeln!(
                    out,
                    "@r{i}\n{}\n+\n{}",
                    random_seq(&mut rng, 150),
                    "I".repeat(150)
                )?;
            }
        }

        // pattern files: name -> (count, length, whether one base is a regex dot)
        let sets = [
            ("fixed100", 100, 10, false),
            ("fixed1000", 1000, 10, false),
            ("regex100", 100, 10, true),
            ("fuzzy20", 20, 20, false),
            ("regex20", 20, 10, true),
            ("regex_hot", 50, 5, true),
        ];
        for (name, count, len, dotted) in sets {
            let mut out = String::new();
            for _ in 0..count {
                let mut seq = random_seq(&mut rng, len).into_bytes();
                if dotted {
                    seq[rng.random_range(0..len)] = b'.';
                }
                out.push_str(&String::from_utf8(seq)?);
                out.push('\n');
            }
            fs::write(fx.path(&format!("{name}.txt")), out)?;
        }

        for (out, inputs) in [("paired.cbq", vec![&r1, &r2]), ("single.cbq", vec![&r1])] {
            let status = Command::new(bin)
                .arg("encode")
                .args(inputs)
                .args(["-o", &fx.path(out)])
                .stderr(Stdio::null())
                .status()?;
            ensure!(status.success(), "encoding {out} failed");
        }
        fs::remove_file(r1)?;
        fs::remove_file(r2)?;
        fs::write(dir.join(".done"), "")?;
        Ok(fx)
    }

    #[allow(clippy::too_many_lines)] // a flat list of cases
    /// Every case. `ACGTAC` and `GTTACA` are fixed 6-mers hitting ~4% of reads.
    fn cases(&self) -> Vec<Case> {
        let (p, s) = (self.path("paired.cbq"), self.path("single.cbq"));
        let list = |name: &str| self.path(&format!("{name}.txt"));
        let (fixed100, fixed1000) = (list("fixed100"), list("fixed1000"));
        let (regex100, regex20, hot) = (list("regex100"), list("regex20"), list("regex_hot"));
        let fuzzy20 = list("fuzzy20");
        let out = self.path("split_out");
        let fz = "ACGTACGTACGTACGTACGT";
        let fz2 = "GTTACAGTTACAGTTACAGT";

        let mut cases = Vec::new();
        let mut add = |name, args: &[&str]| {
            cases.push(Case {
                name,
                args: args.iter().map(ToString::to_string).collect(),
            });
        };

        // aho-corasick (all-ACGT patterns)
        add("ac_count", &["grep", &p, "-C", "ACGTAC"]);
        add("ac_count_rare", &["grep", &p, "-C", "ACGTACGTACGT"]);
        add(
            "ac_count_or_1000",
            &["grep", &p, "-C", "--file", &fixed1000],
        );
        add("ac_out_tsv", &["grep", &p, "ACGTAC"]);
        add("ac_out_color", &["grep", &p, "--color", "always", "ACGTAC"]);
        add(
            "ac_out_color_multi",
            &[
                "grep",
                &p,
                "--or-logic",
                "--color",
                "always",
                "ACGTAC",
                "GTTACA",
            ],
        );
        add("ac_invert_count", &["grep", &p, "-v", "-C", "ACGTAC"]);
        add("ac_and_count", &["grep", &p, "-C", "ACGTAC", "GTTACA"]);
        add(
            "ac_or_count",
            &["grep", &p, "--or-logic", "-C", "ACGTAC", "GTTACA"],
        );
        add(
            "ac_range_count",
            &["grep", &p, "--range", "20..60", "-C", "ACGTAC"],
        );
        add("ac_mate1_count", &["grep", &p, "-m", "1", "-C", "ACGTAC"]);
        add("ac_single_end", &["grep", &s, "-C", "ACGTAC"]);
        add(
            "ac_r_R_count",
            &["grep", &p, "-C", "-r", "ACGTAC", "-R", "GTTACA"],
        );
        let many = [
            "ACGTAC", "GTTACA", "CGTACG", "TTACAC", "ACACAC", "GTGTGT", "CACACA", "TGTGTG",
        ];
        add(
            "ac_and_many_count",
            &[&["grep", &p, "-C"], &many[..]].concat(),
        );
        add("ac_out_tsv_dense", &["grep", &p, "ACGT"]);
        add(
            "ac_out_color_dense",
            &["grep", &p, "--color", "always", "ACGT"],
        );
        add("ac_pc_100", &["grep", &p, "-P", "--file", &fixed100]);
        add("ac_pc_1000", &["grep", &p, "-P", "--file", &fixed1000]);

        // regex
        add("re_count", &["grep", &p, "-C", "ACG.TT"]);
        add("re_count_or_100", &["grep", &p, "-C", "--file", &regex100]);
        add("re_count_or_hot", &["grep", &p, "-C", "--file", &hot]);
        add("re_out_tsv", &["grep", &p, "ACG.TT"]);
        add("re_out_tsv_dense", &["grep", &p, "ACG.T"]);
        add("re_out_color", &["grep", &p, "--color", "always", "ACG.TT"]);
        add(
            "re_out_color_or",
            &[
                "grep",
                &p,
                "--or-logic",
                "--color",
                "always",
                "ACG.TT",
                "TT.ACG",
            ],
        );
        add("re_and_count", &["grep", &p, "-C", "ACG.TT", "TT.ACG"]);
        add(
            "re_or_count",
            &["grep", &p, "--or-logic", "-C", "ACG.TT", "TT.ACG"],
        );
        add("re_invert_count", &["grep", &p, "-v", "-C", "ACG.TT"]);
        add(
            "re_range_count",
            &["grep", &p, "--range", "20..60", "-C", "ACG.TT"],
        );
        add("re_header_count", &["grep", &p, "-H", "-C", "r1[0-9]*5$"]);
        add("re_single_end", &["grep", &s, "-C", "ACG.TT"]);
        add("re_pc_100", &["grep", &p, "-P", "--file", &regex100]);

        // fuzzy
        add("fz_count", &["grep", &p, "-z", "-k1", "-C", fz]);
        add(
            "fz_count_20",
            &["grep", &p, "-z", "-k1", "-C", "--file", &fuzzy20],
        );
        add("fz_out_tsv", &["grep", &p, "-z", "-k1", fz]);
        add(
            "fz_out_color",
            &["grep", &p, "-z", "-k1", "--color", "always", fz],
        );
        add(
            "fz_invert_count",
            &["grep", &p, "-z", "-k1", "-v", "-C", fz],
        );
        add("fz_single_end", &["grep", &s, "-z", "-k1", "-C", fz]);
        add(
            "fz_or_count",
            &["grep", &p, "-z", "-k1", "--or-logic", "-C", fz, fz2],
        );
        add(
            "fz_pc_20",
            &["grep", &p, "-z", "-k1", "-P", "--file", &fuzzy20],
        );

        // split shares the engine
        add(
            "split_ac_100",
            &["split", &p, "--file", &fixed100, "--basepath", &out],
        );
        add(
            "split_regex_20",
            &["split", &p, "--file", &regex20, "--basepath", &out],
        );
        cases
    }
}

fn random_seq(rng: &mut StdRng, len: usize) -> String {
    (0..len)
        .map(|_| ['A', 'C', 'G', 'T'][rng.random_range(0..4)])
        .collect()
}

/// One run of `bin`; the time, or `None` if it failed. Split's output directory
/// is removed first so every run starts from the same filesystem state.
fn timed(bin: &Path, case: &Case, cli: &Cli) -> Option<Duration> {
    let _ = fs::remove_dir_all(cli.dir.join("split_out"));
    let start = Instant::now();
    let status = Command::new(bin)
        .args(&case.args)
        .args(["-T", &cli.threads.to_string()])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .ok()?;
    status.success().then(|| start.elapsed())
}

fn ab(cli: &Cli, fx: &Fixture, bins: [&Path; 2]) -> bool {
    println!("{:<22}{:>9}{:>9}{:>8}", "case", "old_s", "new_s", "ratio");
    let mut slower = false;
    for case in fx.cases() {
        // best of N per binary; start order alternates so neither is always first
        let mut best = [None::<Duration>; 2];
        let mut failed = [false; 2];
        for round in 0..cli.runs + 2 {
            for i in [round % 2, 1 - round % 2] {
                match timed(bins[i], &case, cli) {
                    Some(t) if round >= 2 => best[i] = Some(best[i].map_or(t, |b| b.min(t))),
                    Some(_) => {}
                    None => failed[i] = true,
                }
            }
        }
        let secs = |i: usize| {
            (!failed[i])
                .then(|| best[i].map(|d| d.as_secs_f64()))
                .flatten()
        };
        match (secs(0), secs(1)) {
            (Some(old), Some(new)) => {
                let ratio = new / old;
                let flag = match ratio {
                    r if r > 1.10 => "  SLOWER",
                    r if r < 0.90 => "  faster",
                    _ => "",
                };
                slower |= ratio > 1.10;
                println!("{:<22}{old:>9.4}{new:>9.4}{ratio:>8.2}{flag}", case.name);
            }
            (old, new) => {
                let word = |t: Option<f64>| t.map_or("FAIL".into(), |t| format!("{t:.4}"));
                println!("{:<22}{:>9}{:>9}", case.name, word(old), word(new));
                slower |= new.is_none();
            }
        }
    }
    slower
}

fn check(cli: &Cli, fx: &Fixture, bins: [&Path; 2]) -> bool {
    // one thread, so record order is stable
    let digest = |bin: &Path, case: &Case| {
        let out = Command::new(bin)
            .args(&case.args)
            .args(["-T", "1"])
            .stderr(Stdio::null())
            .output()
            .ok()?;
        let mut hasher = DefaultHasher::new();
        out.stdout.hash(&mut hasher);
        Some(hasher.finish())
    };
    let mut differs = false;
    for case in fx.cases() {
        let _ = fs::remove_dir_all(cli.dir.join("split_out"));
        let (old, new) = (digest(bins[0], &case), digest(bins[1], &case));
        let verdict = if old == new { "same" } else { "DIFF" };
        differs |= old != new;
        println!("{:<22}{verdict}", case.name);
    }
    differs
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let (Mode::Ab { old, new } | Mode::Check { old, new }) = &cli.mode;
    let bins = [old.canonicalize()?, new.canonicalize()?];
    let fx = Fixture::ensure(&cli.dir, cli.records, &bins[0])?;
    let bins = [bins[0].as_path(), bins[1].as_path()];
    let failed = match cli.mode {
        Mode::Ab { .. } => ab(&cli, &fx, bins),
        Mode::Check { .. } => check(&cli, &fx, bins),
    };
    std::process::exit(i32::from(failed));
}
